// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:miracle/Models/days.dart';
import 'package:miracle/Models/delneveshteh_model.dart';
import 'package:miracle/Models/review.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DaysModelAdapter());
    registerAdapter(DelneveshtehModelAdapter());
    registerAdapter(ReviewModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DaysModelAdapter());
    registerAdapter(DelneveshtehModelAdapter());
    registerAdapter(ReviewModelAdapter());
  }
}
